# Generated by Django 6.0.5 on 2026-05-23 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_path', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('num_days', models.IntegerField()),
                ('customer_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(30)])),
                ('customer_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('customer_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('customer_address', models.TextField(validators=[django.core.validators.MinLengthValidator(30), django.core.validators.MaxLengthValidator(100)])),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Netbanking', 'Netbanking'), ('Card', 'Credit/Debit Card'), ('Pay on Visit', 'Pay on Visit')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.vehicle')),
            ],
        ),
    ]
