# Generated by Django 6.0.5 on 2026-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.CharField(default='', max_length=50),
        ),
    ]
