# Generated by Django 6.0.5 on 2026-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_vehicle_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=20),
        ),
    ]
