# Generated by Django 6.0.5 on 2026-05-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_booking_rejection_reason_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=15),
        ),
    ]
