# Generated by Django 6.0.5 on 2026-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_booking_customer_email_booking_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_proof_2',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof_3',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof_4',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof_5',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
