# Generated by Django 6.0.5 on 2026-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_booking_id_proof_2_booking_id_proof_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='utr_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
