# Generated by Django 6.0.5 on 2026-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_booking_utr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
