# Generated by Django 6.0.5 on 2026-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_booking_prepaid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
